### ISSUE TITLE
The result I reproduced is almost 0.

### ISSUE THREAD

**Issue by gaby20000413** [Czm369/MixPL#9]
I followed [this website](https://mmdetection.readthedocs.io/zh-cn/latest/user_guides/semi_det.html) to download the COCO dataset and trained the model by splitting the dataset accordingly.
config: \projects\MixPL\configs\mixpl_faster-rcnn_r50-caffe_fpn_180k_coco-s1-p10.py
train: \tools\train.py
hardware: GPU RTX 2070 super
My result of validation is almost 0 (mAP 0.001).
There is no error during training. Is there any suggestion? Thank you.

**Comment by Czm369** [comment]
More details, such as config and log, please.

**Comment by gaby20000413** [comment]
Config is the same as yours, and no changes have been made.
This is my train log:
[20240312_204710.log](https://github.com/Czm369/MixPL/files/14582791/20240312_204710.log)
Thank you for your reply.

**Comment by PAGF188** [comment]
The Faster RCNN config [(config)](https://github.com/Czm369/MixPL/blob/main/projects/MixPL/configs/mixpl_faster-rcnn_r50-caffe_fpn_180k_coco-s1-p10.py) has an error and perform the evaluation each 50 training iterations:

https://github.com/Czm369/MixPL/blob/9f2176a3e4df8bcc12e8dc0be2e62decbaae9781/projects/MixPL/configs/mixpl_faster-rcnn_r50-caffe_fpn_180k_coco-s1-p10.py#L70-L72

The bbox_mAP you are getting is the AP after training the model in only 1100 iterations out of the 180K needed (that's why you get 0).

**Comment by Czm369** [comment]
`val_interval=5000`

**Comment by tamama9018** [comment]
Thanks for your great work!
I tried the exact same method in 180K interations (I changed only `val_interval=5000`) and mAP gave the following results.
```
2024/03/15 20:47:31 - mmengine - INFO - bbox_mAP_copypaste: 0.112 0.226 0.097 0.054 0.123 0.151
2024/03/15 20:47:31 - mmengine - INFO - Iter(val) [5000/5000]    teacher/coco/bbox_mAP: 0.1490  teacher/coco/bbox_mAP_50: 0.2720  teacher/coco/bbox_mAP_75: 0.1480  teacher/coco/bbox_mAP_s: 0.0790  teacher/coco/bbox_mAP_m: 0.1580  teacher/coco/bbox_mAP_l: 0.2010  student/coco/bbox_mAP: 0.1120  student/coco/bbox_mAP_50: 0.2260  student/coco/bbox_mAP_75: 0.0970  student/coco/bbox_mAP_s: 0.0540  student/coco/bbox_mAP_m: 0.1230  student/coco/bbox_mAP_l: 0.1510  data_time: 0.0071  time: 0.0399
2024/03/15 20:47:31 - mmengine - INFO - Saving checkpoint at 1 epochs
```
This is my train log:
[20240314_032925.log](https://github.com/Czm369/MixPL/files/14717704/20240314_032925.log)

I don't seem to have reached the mAP described in the paper (37.16 ± 0.15 ), am I doing it right?
I would be happy to receive a reply.
